### ISSUE TITLE
Replace non-ontological properties

### ISSUE THREAD

**Issue by edgardmarx** [AKSW/life-knowledge-base#2]
Replace
```

http://rs.gbif.org/terms/1.0/isMarine 
http://rs.gbif.org/terms/1.0/isFreshwate
http://rs.gbif.org/terms/1.0/isTerrestrial
```

by environment property i.e.

?s <http://.../enviroment>  <http://../marine>
?s <http://.../enviroment>  <http://../freshwater>
?s <http://.../enviroment>  <http://../terrestrial>

There are other environments i.e, see here `https://www.marinespecies.org/echinoidea/aphia.php?p=taxdetails&id=123105`

**Comment by JLXE5** [comment]
fixed with 1eb61611cdc8d49e23f0fa7637cdb40e1a9d63db.
