### ISSUE TITLE
Encode URIs

### ISSUE THREAD

**Issue by edgardmarx** [AKSW/life-knowledge-base#5]
Some URIs are not encoded therefore causing parser errors.

**Comment by JLXE5** [comment]
Do you have any hints on which can't be parsed?

If this is about the `mrgid:`: this can be seen as a mistake in the original COL and has been circumvented in this repo in the meantime.

**Comment by edgardmarx** [comment]
Just encode all URIs using URI encoding or, try to upload it to stardog

i.e.

`ns1:3TR9D	ns6:references	ns5:?deeplink=Leptomeria-aphylla ;`

should be

`ns1:3TR9D	ns6:references	ns5:%3Fdeeplink%3DLeptomeria-aphylla ;`

**Comment by JLXE5** [comment]
> `ns1:3TR9D ns6:references ns5:?deeplink=Leptomeria-aphylla ;`
> 
> should be
> 
> `ns1:3TR9D ns6:references ns5:%3Fdeeplink%3DLeptomeria-aphylla ;`

This is the example/hint I was hoping for, thank you. 
I'll check later if the issue persists in the current version of `parser.py`.

**Comment by JLXE5** [comment]
> `ns1:3TR9D ns6:references ns5:?deeplink=Leptomeria-aphylla ;`
> 
> should be
> 
> `ns1:3TR9D ns6:references ns5:%3Fdeeplink%3DLeptomeria-aphylla ;`

This is the example/hint I was hoping for, thank you. 
I'll check later if the issue persists in the current version of `parser.py`.

**Comment by JLXE5** [comment]
> `ns1:3TR9D ns6:references ns5:?deeplink=Leptomeria-aphylla ;`
> 
> should be
> 
> `ns1:3TR9D ns6:references ns5:%3Fdeeplink%3DLeptomeria-aphylla ;`

This is the example/hint I was hoping for, thank you. 
I'll check later if the issue persists in the current version of `parser.py`.

**Comment by JLXE5** [comment]
fixed with fc3845410e49fd6308685dc301549bc068c040a9
